### ISSUE TITLE
Hardcoded non https

### ISSUE THREAD

**Issue by nordic** [leen3o/mvcforum#11]
Hi, i found this code. This is no good if i have https on website.

       public static string GetGravatarImage(string email, int size)
        {
            return IsValidEmail(email) ? string.Format("http://www.gravatar.com/avatar/{0}?s={1}", md5HashString(email), size) : "";
        }

**Comment by PhonicUK** [comment]
All that's required is to change the uri from http:// to // and the browser will use the same protocol.

**Comment by ryios** [comment]
Better yet, create a constant for that url, something like

const string gravatarUrl = "{0}://www.gravatar.com/avatar/{1}?s={2}";

public static string GetGravatarImage(string email, int size)
{
    return IsValidEmail(email) ? string.Format(HttpContext.Current.Request.Url.Scheme, md5HashString(email), size): "";
}

Using // is a hack that can cause problems down the line, like with Http 3X redirects or browsers in strict modes...

**Comment by leen3o** [comment]
This is fixed in v1.7
