### ISSUE TITLE
Missing resource string

### ISSUE THREAD

**Issue by nordic** [leen3o/mvcforum#12]
i found missing resource string.

![sfxce4l](https://cloud.githubusercontent.com/assets/366576/7035760/6b822efc-dd8c-11e4-9bac-68aab3e8a677.png)

TOPICS.HOTTOPICS

**Comment by songoku119** [comment]
Found this issue the other day too. Change the string name to TOPIC.HOTTOPICS

**Comment by leen3o** [comment]
This is fixed in v1.7
