### ISSUE TITLE
Improved password reset suggestion

### ISSUE THREAD

**Issue by davidglenn** [leen3o/mvcforum#16]
Hi, first up, MvcForum is great. Thanks for making your hard work open source for everybody.

I wanted to make a little suggestion to improve the security of the password reset functionality.

Currently to reset a user's password, a user enters their registered email address on the Forgot Password form. The password for the email address is then reset to a new temporary password and the new password is emailed to that address. 

This process doesn't validate that the request originator is the registered user before reseting the password. Therefore any visitor to the site can reset a registered user's password by simply knowing the email address which they registered with. As well as being annoying this can potentially enable a malicious user to lock a register user out, a kind of DOS.

A more secure approach would be to email a unique password reset URL to the registered email address. The URL is valid for one use only within a limited time period and points to a page where the user can enter a new password. The important part is that the password is not reset until the user follows the URL and enters a new password.

Troy Hunt has a detailed explanation at http://www.troyhunt.com/2012/05/everything-you-ever-wanted-to-know.html

There is a working example that I am currently testing on my fork https://github.com/davidglenn/mvcforum/commit/691ac0d557f0c5f23bdab80f672c504eadfd2ca4

I am fairly new to GitHub but would be willing to work on the code to get it to a suitable state for a pull request if you were interested.

If not, then thanks again for the project.

**Comment by joshyates1980** [comment]
David,  good fix.  You got my vote.  Plus, it's less code and less annoying then security questions.

**Comment by leen3o** [comment]
Thanks for the heads up. And thanks for taking the time to suggest and come up with the code :) Looks good from a glance. I'm a couple of weeks off being able to start the next release (But will definitely implement this).

**Comment by davidglenn** [comment]
Great, I look forward to seeing it implemented in the next version.

**Comment by leen3o** [comment]
Thanks again for this. I have implemented it into v1.7
