### ISSUE TITLE
Post editor and parser strange behaviour

### ISSUE THREAD

**Issue by Nekroido** [leen3o/mvcforum#19]
I am using BB Editor, but the parser translates markdown's "> text" to block quotes.
"?v=videocode" is added after embeds and [youtube]videocode[/youtube] is ignored. And the editor itself looks broken, though can be easily fixed by ".sceditor-toolbar * { box-sizing: content-box; }".
There's also no option to add or edit BB tags without forking the code.

**Comment by leen3o** [comment]
Sorry the BB Editor is no longer supported
