### ISSUE TITLE
Don't show categories in create form you don't have create permissions on

### ISSUE THREAD

**Issue by mattbrailsford** [leen3o/mvcforum#30]
Right now, in the create discussion form, it will show all categories as long as you don't have a "deny access" permission to, but it should also take into account whether you have create topic permissions as you only find this out when you click create and get an error message. It would be better to just not show it as a category at all.

Maybe you can extend the GetAllowedCategories method to accept a ActionType enum with options such as View, Create, Edit, Delete. That way you can request allowed categories for a given action as you may want to just check View access in some places (ie, for listing categories) but in other, such as here in the create dialog, you want to check Create permissions.

**Comment by leen3o** [comment]
This is done in v1.7 - I haven't used an enum as I can't make it partial, it would make it difficult to allow people to create their own new permissions. So I have just stuck with a string, as we already have AppConstants for the default permissions you still get a certain amount of intellisense.

Usage like so

    var allowedAccessCategories = _categoryService.GetAllowedCategories(UsersRole);
    var allowedCreateTopicCategories = _categoryService.GetAllowedCategories(UsersRole, AppConstants.PermissionCreateTopics);
