### ISSUE TITLE
Error for sql server 2008

### ISSUE THREAD

**Issue by asemandeveloper** [leen3o/mvcforum#31]
In version 1.7 if I change .\SQLExpress to sql server name, Program shows error.
```
<add name="MVCForumContext" connectionString="data source=.\SQLExpress;database=mvcforum;Trusted_Connection=True;" providerName="System.Data.SqlClient"/>
```
```
<add name="MVCForumContext" connectionString="Data Source=sqlservername;Initial Catalog=mvcforum;Persist Security Info=True;Integrated Security=True;" providerName="System.Data.SqlClient" />
```

**Comment by leen3o** [comment]
Unfortunately I need way more information than that? Is the SQL server name correct? Does the database exists? Without examples of the error I cannot help.

**Comment by asemandeveloper** [comment]
yes SQL Server name is correct and database is available

**Comment by leen3o** [comment]
Unless you can give me more information I can't help you.
