### ISSUE TITLE
jquery-ui-1.10.3.min.js missing

### ISSUE THREAD

**Issue by nordic** [leen3o/mvcforum#4]
Hi. I provide clean install and this is error on latest version (1.6) 

![](http://i.imgur.com/WBflhUt.png)

**Comment by leen3o** [comment]
Ahh one sec will push a fix

**Comment by leen3o** [comment]
That'll teach me to remove something without double checking it's still referenced!! It's just a case of removing the line pointing to jquery-ui (As it doesn't exist anymore). 

Have updated the release and the source
