### ISSUE TITLE
Unable to delete attach files

### ISSUE THREAD

**Issue by wezmag** [leen3o/mvcforum#40]
When try to delete an attach, an error occurs.
![error3](https://cloud.githubusercontent.com/assets/340794/9783634/73993646-57d8-11e5-914d-ba64e5500639.png)
The error is happened in UploadController.cs, here is a screen shot
![error](https://cloud.githubusercontent.com/assets/340794/9783658/ab19c7f2-57d8-11e5-9161-e9ff0bd85a3c.png)
I couldn't to fix it, because I am new to ASP.NET MVC. :(

**Comment by leen3o** [comment]
Thanks will investigate and fix

**Comment by wezmag** [comment]
I remove line 48 `.AsNoTracking()` in UploadedFileRepository.cs,  everything works as expected.

**Comment by leen3o** [comment]
Fixed in v1.7 - thanks.
