### ISSUE TITLE
Bug in MemberRegisterLogic in MemberController.cs

### ISSUE THREAD

**Issue by wezmag** [leen3o/mvcforum#48]
>if (userModel.LoginType == LoginType.**Google**)
  {
       userToSave.MicrosoftAccessToken = userModel.UserAccessToken;
  }

https://github.com/leen3o/mvcforum/blob/master/MVCForum.Website/Controllers/MembersController.cs#L427

**Comment by leen3o** [comment]
Thanks :+1: Fixed in v1.8
