### ISSUE TITLE
Breadcrum breaks after rearranging categories

### ISSUE THREAD

**Issue by mutzl** [leen3o/mvcforum#52]
Steps to reproduce:
1.) Create new Category A
2.) Create another Category B
3.) Edit Category A and make it a child of B

Breadcumbs will now break, because current algorithm depends on the order of items returned from the database query. (A is still before B in the database.)

Fix in CategoryRepository Line 40+(https://github.com/leen3o/mvcforum/blob/master/MVCForum.Data/Repositories/CategoryRepository.cs)

		public IList<Category> Get(IList<Guid> ids, bool fullGraph = false)
		{
			IList<Category> categories;
				
			if (fullGraph)
			{
				categories =
					_context.Category.AsNoTracking()
						.Include(x => x.Topics.Select(l => l.LastPost.User))
						.Include(x => x.ParentCategory)
						.Where(x => ids.Contains(x.Id))
						.ToList();
			}
			else
			{
				categories = _context.Category
					.AsNoTracking().Where(x => ids.Contains(x.Id)).ToList();
			}

			// make sure categories are returned in order of ids (not in Database order)
			return ids.Select(id => categories.Single(c => c.Id == id)).ToList();
		}

**Comment by leen3o** [comment]
Thanks have added this to v1.8
