### ISSUE TITLE
Admin can not mark a post as solution.

### ISSUE THREAD

**Issue by wezmag** [leen3o/mvcforum#53]
https://github.com/leen3o/mvcforum/blob/master/MVCForum.Website/Views/Shared/_Post.cshtml#L169
In the view above, it shows that Admin can mark a post as solution.
But in TopicService.SolveTopic, only the topic owner can do this.
https://github.com/leen3o/mvcforum/blob/master/MVCForum.Services/TopicService.cs#L359

**Comment by leen3o** [comment]
Fixed in v1.8 - Thanks
