### ISSUE TITLE
Missing NuGet.exe file

### ISSUE THREAD

**Issue by davidglenn** [leen3o/mvcforum#6]
The 1.6 Source code (zip) is missing `/.nuget/NuGet.exe` causing the build to fail. The current master is also missing the same file.

**Comment by leen3o** [comment]
I have now added it. Thanks. Trying out AppVeyor so this doesn't happen again.

**Comment by davidglenn** [comment]
Thanks for the quick response. 

FYI the dependency on `NuGet.exe` (and the whole `/.nuget` folder) can be removed if the project is upgraded to use automatic package restore instead of the current MSBuild-Integrated package restore <https://docs.nuget.org/Consume/Package-Restore/Migrating-to-Automatic-Package-Restore>. Requires NuGet 2.7+

I'm happy to make a pull request if you want.

**Comment by leen3o** [comment]
Please do
