### ISSUE TITLE
Bug in Admin -> Moderate -> Show More Topic

### ISSUE THREAD

**Issue by wezmag** [leen3o/mvcforum#60]
Hi Lee,
I found a bug in Admin -> Moderate -> Show More Topics.
Supposing that page size is 5, and I have 11 topics to be reviewed.
When I entered the Moderate page, I saw the first 5 topic.
Then I approved all of them.
Then I clicked on "Show More Topics".
Instead of getting next 5 topics, I only got 1 topic. 
I think that's because there were only 6 pending topics left in the database, the second page has only 1 topic.

**Comment by leen3o** [comment]
This has been completely changed in v1.8. Thanks for the report.
