### ISSUE TITLE
Initial build

### ISSUE THREAD

**Issue by joshyates1980** [leen3o/mvcforum#8]
After I build the solution, I am receiving multiple missing nuget packages from the solution.  The nuget restore also fails.  Any advice would be much appreciated.  
![mvcforum](https://cloud.githubusercontent.com/assets/7255545/6449966/4361a7fe-c0ea-11e4-9455-e7112bab4e19.png)
![mvcforum2](https://cloud.githubusercontent.com/assets/7255545/6450242/2574498e-c0ec-11e4-8cbc-8d984d2c0e95.png)

**Comment by leen3o** [comment]
I've recently merged a pull request to upgrade Nuget so it auto downloads packages. It would seem this is not working. Could you try deleting that packages.config file and the rebuilding and let me know if that fixes it for you.

**Comment by joshyates1980** [comment]
After deleting the package.config, the result is still the same.  fyi, your site is also down:  http://www.mvcforum.com.   I'm looking forward to having a look at this project.

**Comment by leen3o** [comment]
No problem. I'll revert it back in the morning as it was working fine previously. Website is working fine for me?

**Comment by leen3o** [comment]
Should all be back working as normal now

**Comment by joshyates1980** [comment]
The reason I couldn't get your site to load was because of my proxy at work.  I got your site to load on through my cellular network.

I'm still getting the same on initial build. 
![mvcforum3](https://cloud.githubusercontent.com/assets/7255545/6464311/01f62a84-c17f-11e4-9b3c-42ad46ec065e.png)

**Comment by leen3o** [comment]
It's a nuget problem. Did you do a fresh clone/download?

It's trying to restore the packages but can't. Is this the same issue as the website, because of the proxy? It can't get the packages from Nuget?

**Comment by leen3o** [comment]
I have this in AppVeyor and it's building fine. But that's because it can download the packages. Also you do have Nuget installed right?

**Comment by joshyates1980** [comment]
Yes, I did a fresh download.
hmmm....maybe it is a proxy issue.  Yes, I'm using Nuget 2.8+ with VS2013 Pro

**Comment by joshyates1980** [comment]
Ok.  I guess that download wasn't as fresh as I thought.  I got it to compile on my other computer just fine.  This looks like a great project!  Good work.  I'm going to Fork it.

I am getting runtime errors on some of the pages when the site tries to hit www.mvcforum.com because of my internal network.
